Hardware:
  Processor:
    Cores: 1
    ThreadsPerCore: 1
    ISA: 32
    MMU: Yes
    FPU: No

  Memory:
    MaxPhysicalAddrBitWidth: 36
    Flash:
      StartAddr: 0x0
      SizeInMegaBytes: 16
      Permissions: RXC
    RAM:
      StartAddr: 0x40000000
      SizeInMegaBytes: 4
      Permissions: RWXC
    MMIO:
      StartAddr: 0xFFFF0000
      EndAddr: 0xFFFFFFFF
      Permissions: RW

  Devices:
    - Name: Timer
      MemoryRegion:
        StartAddr: 0xFFFF3100
        SizeInBytes: 256
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3100
    - Name: InterruptController
      MemoryRegion:
        StartAddr: 0xFFFF3000
        SizeInBytes: 32
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3000
    - Name: Serial
      MemoryRegion:
        StartAddr: 0xFFFF3200
        SizeInBytes: 64
        Permissions: RW
      NamedRegisters:
        Control: 0xFFFF3200
        TX: 0xFFFF3204
        RX: 0xFFFF3208
    - Name: ScratchArea
      MemoryRegion:
        StartAddr: 0xFFFF2C00
        SizeInBytes: 1024
        Permissions: RW

Software:
  BuildAndExecute:
    LogLevel: NONE
    OptimizationLevel: 2
    Debug: No
  ProgramThreads:
    - CortosInitCalls:
        - main
      StackSize:
        SizeInKiloBytes: 256

ExtraCc:
  - tflite-micro/tensorflow/lite/micro/examples/hello_world/hello_world_test.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/hello_world/models/hello_world_float_model_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/hello_world/models/hello_world_int8_model_data.cc
  - os/rtos/cortos2/examples/tflite/cxxstub.cc

ExtraIncludes:
  - tflite-micro
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/gemmlowp
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/kissfft
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/ruy

ExtraLibDirs:
  - tflite-micro/gen/ajit_sparc_default_gcc/lib
