# yaml configuration file for linker/loader of Co-RTOS

Cores: 1
ThreadsPerCore: 1
TotalMemoryInKB: 8192
LogLevel: NONE

ProgramThreads:
  - CortosInitCalls:
      - tflite_cortos_start
    StackSizeInBytes: 65536

ExtraCc:
  - tflite-micro/tensorflow/lite/micro/examples/micro_speech/micro_speech_test.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/models/micro_speech_quantized_model_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/models/audio_preprocessor_int8_model_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/no_1000ms_audio_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/yes_1000ms_audio_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/silence_1000ms_audio_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/noise_1000ms_audio_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/no_30ms_audio_data.cc
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles/tensorflow/lite/micro/examples/micro_speech/testdata/yes_30ms_audio_data.cc
  - os/rtos/cortos/examples/tflite/cxxstub.cc

ExtraIncludes:
  - tflite-micro
  - tflite-micro/gen/ajit_sparc_default_gcc/genfiles
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/gemmlowp
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/flatbuffers/include
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/kissfft
  - tflite-micro/tensorflow/lite/micro/tools/make/downloads/ruy

ExtraLibDirs:
  - tflite-micro/gen/ajit_sparc_default_gcc/lib
